### ISSUE TITLE
Crash del gioco su quest Spirito Nero

### ISSUE THREAD

**Issue by EvilRex** [Master-Antonio/Black-Desert-Online-Italiano#5]
Ciao, ho inserito la traduzione del gioco.

Tutto ok , tradotto nei menu e in-game.

Solo che provando a richiamare lo spirito nero, e andando sulla sezione "Quest" mi si chiude il gioco e necessito di ri-aprirlo.

E' un errore dovuto alla traduzione dato che re-inserendo la versione originale (quella inglese), sono riuscito a recuperare correttamente la quest.

Ho provato a questo punto a re-inserire nuovamente la patch in italiano, ma stesso problema quando provo a richiamare lo spirito.

Non so , consiglierei di eseguire un compare sulla vecchia e sulla nuova versione, in modo da capire se ci fossero dei nodi che mancano o addirittura qualche tag per il font non correttamente chiuso.

Resto in attesa di info :) Grazie per l'enorme lavoro.

**Comment by Master-Antonio** [comment]
Utilizzi per caso altre mod? Tipo font diversi e cosi via, perchè questo crash ti posso confermare che non c'è, non lo causa il crash.
Ti uppo anche l'immagine di un membro del team.
![image](https://user-images.githubusercontent.com/9674957/79227311-fb388680-7e5f-11ea-8877-c01d9c31ef9b.png)

Puoi farci lo screen della versione in Inglese, grazie.

**Comment by Master-Antonio** [comment]
Puoi mandarci il tuo log del gioco, grazie mille.

**Comment by EvilRex** [comment]
[Client_20200414184357.log](https://github.com/Master-Antonio/Black-Desert-Online-Italiano/files/4476635/Client_20200414184357.log)
[Client.log](https://github.com/Master-Antonio/Black-Desert-Online-Italiano/files/4476637/Client.log)
[StartupLog_202004144357.log](https://github.com/Master-Antonio/Black-Desert-Online-Italiano/files/4476638/StartupLog_202004144357.log)
[launcher_20200414_184318_10596.log](https://github.com/Master-Antonio/Black-Desert-Online-Italiano/files/4476639/launcher_20200414_184318_10596.log)

**Comment by EvilRex** [comment]
Aggiungo inoltre che , lo stesso crash lo ricevo quando provo ad andare da un Npc.

**Comment by Master-Antonio** [comment]
Dove? Che npc? A che ora?
