### ISSUE TITLE
Nella selezione personaggi

### ISSUE THREAD

**Issue by Hysabell** [Master-Antonio/Black-Desert-Online-Italiano#6]
Ho scaricato il file, sono nel menu della scelta del personaggio e ho notato la voce elimina carattere, volevo segnalare che l'adattamento migliore sarebbe "elimina personaggio".

**Comment by AlessandroZaino91** [comment]
Ciao si  al momento la traduzione presente è molto acerba ma è in continuo aggiornamento e miglioramento . Purtroppo siamo alla ricerca di persone che vogliano contribuire alla traduzione , quindi qualora ti vada di dare una mano ,qualsiasi aiuto è per noi un'opportunità per poter avere risultati nel piu breve tempo possibile . 
Un Abbraccio.
