### ISSUE TITLE
Crash vari

### ISSUE THREAD

**Issue by dhz1234** [Master-Antonio/Black-Desert-Online-Italiano#7]
Ciao

Ti segnalo alcuni crash.
1) Prima interazione durante il tutorial con lo spirito nero. Subito cercando di premere R per ottenere la quest, il gioco crasha
2) Durante le missioni attaccando i "quest object" tendenzialmente crasha. Purtroppo tendenzialmente perchè lo fa circa 1 volta su 2.
Di questo secondo crash provo a passarti il log del client. La quest è una delle prime, il pg è ancora al lv 9

[Client_20200414184802.log](https://github.com/Master-Antonio/Black-Desert-Online-Italiano/files/4476662/Client_20200414184802.log)

**Comment by Swordmoon91** [comment]
Ciao , siamo al corrente di questo problema e siamo al lavoro per una soluzione :)
Ti ringraziamo per il log allegato.
